<a href="https://colab.research.google.com/github/shade-9/python/blob/main/7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


2. Write a python program to calculate the sum of all columns in a 2D NumPy array.

In [ ]:
import numpy as np

data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

column_sums = np.sum(data, axis=0)

print("Sum of all columns:",column_sums)

Sum of all columns: [12 15 18]


3. Create two NumPy arrays representing monthly high and low temperatures for a year. Calculate the monthly average temperatures, the overall average high and low temperatures, and identify the months with the highest and lowest average temperatures.


In [ ]:
high_temps = np.array([25, 28, 30, 32, 35, 38, 40, 37, 33, 29, 27, 24])

low_temps = np.array([15, 18, 20, 22, 25, 28, 30, 27, 23, 19, 17, 14])

monthly_avg_temps = (high_temps + low_temps) / 2

overall_avg_high = np.mean(high_temps)
overall_avg_low = np.mean(low_temps)

max_avg_temp_month = np.argmax(monthly_avg_temps) + 1
min_avg_temp_month = np.argmin(monthly_avg_temps) + 1

print("Monthly Average Temperatures:", monthly_avg_temps)
print("Overall Average High Temperature:", overall_avg_high)
print("Overall Average Low Temperature:", overall_avg_low)
print("Month with Highest Average Temperature:", max_avg_temp_month)
print("Month with Lowest Average Temperature:", min_avg_temp_month)

Monthly Average Temperatures: [20. 23. 25. 27. 30. 33. 35. 32. 28. 24. 22. 19.]
Overall Average High Temperature: 31.5
Overall Average Low Temperature: 21.5
Month with Highest Average Temperature: 7
Month with Lowest Average Temperature: 12


In [ ]:
random_integer = np.random.randint(0, 101)

print("Random Integer:", random_integer)

Random Integer: 41
